common:
  output_directory: datasets/
  default_n_jobs: 4
steps:
  - type: preprocess
    parameters:
      inputs: 
      - WikiMatrix.en-ru.en
      - WikiMatrix.en-ru.ru
      outputs: &preprocessed
      - en_preprocessed.en
      - ru_preprocessed.ru
      preprocessors:
        - WhitespaceNormalizer: {}
        - CustomPreprocessor: {}
          module: custom_preprocessor
  - type: remove_duplicates
    parameters:
      inputs: *preprocessed
      outputs: &no_duplicates
        - en_no_duplicates.en
        - ru_no_duplicates.ru     
              
              
              
      